#!/bin/bash

rm -rf {{ cookiecutter.project_name }}_auth/migrations
rm -rf {{ cookiecutter.app_name }}/migrations
./manage.py makemigrations {{ cookiecutter.app_name }} {{ cookiecutter.project_name }}_auth
./manage.py migrate